/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalSWEUIBKParser;
import org.xtext.example.mydsl.services.SWEUIBKGrammarAccess;

public class SWEUIBKParser extends AbstractAntlrParser {

	@Inject
	private SWEUIBKGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSWEUIBKParser createParser(XtextTokenStream stream) {
		return new InternalSWEUIBKParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public SWEUIBKGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SWEUIBKGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
