/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SWEUIBKStandaloneSetup extends SWEUIBKStandaloneSetupGenerated {

	def static void doSetup() {
		new SWEUIBKStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
