/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.sWEUIBK;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Analyzer Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getAnalyzerDeclaration()
 * @model
 * @generated
 */
public interface AnalyzerDeclaration extends ObjectDeclaration
{
} // AnalyzerDeclaration
