/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.sWEUIBK;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domainmodel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sWEUIBK.Domainmodel#getElements <em>Elements</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sWEUIBK.Domainmodel#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getDomainmodel()
 * @model
 * @generated
 */
public interface Domainmodel extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.sWEUIBK.ObjectDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getDomainmodel_Elements()
   * @model containment="true"
   * @generated
   */
  EList<ObjectDeclaration> getElements();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.sWEUIBK.ObjectAction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getDomainmodel_Actions()
   * @model containment="true"
   * @generated
   */
  EList<ObjectAction> getActions();

} // Domainmodel
