/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.sWEUIBK;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getModelAction()
 * @model
 * @generated
 */
public interface ModelAction extends ObjectAction
{
} // ModelAction
