/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.sWEUIBK;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Monitor Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sWEUIBK.MonitorDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sWEUIBK.MonitorDeclaration#getUrl <em>Url</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getMonitorDeclaration()
 * @model
 * @generated
 */
public interface MonitorDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(Monitor)
   * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getMonitorDeclaration_Name()
   * @model containment="true"
   * @generated
   */
  Monitor getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sWEUIBK.MonitorDeclaration#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(Monitor value);

  /**
   * Returns the value of the '<em><b>Url</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Url</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' containment reference.
   * @see #setUrl(MonitorInitialization)
   * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getMonitorDeclaration_Url()
   * @model containment="true"
   * @generated
   */
  MonitorInitialization getUrl();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sWEUIBK.MonitorDeclaration#getUrl <em>Url</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' containment reference.
   * @see #getUrl()
   * @generated
   */
  void setUrl(MonitorInitialization value);

} // MonitorDeclaration
