/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.sWEUIBK;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getObjectDeclaration()
 * @model
 * @generated
 */
public interface ObjectDeclaration extends EObject
{
} // ObjectDeclaration
