/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.sWEUIBK;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Page Object Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sWEUIBK.PageObjectAction#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sWEUIBK.PageObjectAction#getMethod <em>Method</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getPageObjectAction()
 * @model
 * @generated
 */
public interface PageObjectAction extends ObjectAction
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.sWEUIBK.PageOperations}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see org.xtext.example.mydsl.sWEUIBK.PageOperations
   * @see #setValue(PageOperations)
   * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getPageObjectAction_Value()
   * @model
   * @generated
   */
  PageOperations getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sWEUIBK.PageObjectAction#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see org.xtext.example.mydsl.sWEUIBK.PageOperations
   * @see #getValue()
   * @generated
   */
  void setValue(PageOperations value);

  /**
   * Returns the value of the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Method</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method</em>' attribute.
   * @see #setMethod(String)
   * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage#getPageObjectAction_Method()
   * @model
   * @generated
   */
  String getMethod();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sWEUIBK.PageObjectAction#getMethod <em>Method</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method</em>' attribute.
   * @see #getMethod()
   * @generated
   */
  void setMethod(String value);

} // PageObjectAction
