/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.sWEUIBK;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKPackage
 * @generated
 */
public interface SWEUIBKFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SWEUIBKFactory eINSTANCE = org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Domainmodel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Domainmodel</em>'.
   * @generated
   */
  Domainmodel createDomainmodel();

  /**
   * Returns a new object of class '<em>Object Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Declaration</em>'.
   * @generated
   */
  ObjectDeclaration createObjectDeclaration();

  /**
   * Returns a new object of class '<em>Model Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Declaration</em>'.
   * @generated
   */
  ModelDeclaration createModelDeclaration();

  /**
   * Returns a new object of class '<em>Monitor Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Monitor Declaration</em>'.
   * @generated
   */
  MonitorDeclaration createMonitorDeclaration();

  /**
   * Returns a new object of class '<em>Analyzer Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Analyzer Declaration</em>'.
   * @generated
   */
  AnalyzerDeclaration createAnalyzerDeclaration();

  /**
   * Returns a new object of class '<em>Analyzer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Analyzer</em>'.
   * @generated
   */
  Analyzer createAnalyzer();

  /**
   * Returns a new object of class '<em>Page Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Declaration</em>'.
   * @generated
   */
  PageDeclaration createPageDeclaration();

  /**
   * Returns a new object of class '<em>Object Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Action</em>'.
   * @generated
   */
  ObjectAction createObjectAction();

  /**
   * Returns a new object of class '<em>Model Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Action</em>'.
   * @generated
   */
  ModelAction createModelAction();

  /**
   * Returns a new object of class '<em>Monitor Object Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Monitor Object Action</em>'.
   * @generated
   */
  MonitorObjectAction createMonitorObjectAction();

  /**
   * Returns a new object of class '<em>Analyzer Object Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Analyzer Object Action</em>'.
   * @generated
   */
  AnalyzerObjectAction createAnalyzerObjectAction();

  /**
   * Returns a new object of class '<em>Page Object Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Object Action</em>'.
   * @generated
   */
  PageObjectAction createPageObjectAction();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SWEUIBKPackage getSWEUIBKPackage();

} //SWEUIBKFactory
