/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.sWEUIBK;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.sWEUIBK.SWEUIBKFactory
 * @model kind="package"
 * @generated
 */
public interface SWEUIBKPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sWEUIBK";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/SWEUIBK";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sWEUIBK";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SWEUIBKPackage eINSTANCE = org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.DomainmodelImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getDomainmodel()
   * @generated
   */
  int DOMAINMODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__ELEMENTS = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__ACTIONS = 1;

  /**
   * The number of structural features of the '<em>Domainmodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.ObjectDeclarationImpl <em>Object Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.ObjectDeclarationImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getObjectDeclaration()
   * @generated
   */
  int OBJECT_DECLARATION = 1;

  /**
   * The number of structural features of the '<em>Object Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_DECLARATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.ModelDeclarationImpl <em>Model Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.ModelDeclarationImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getModelDeclaration()
   * @generated
   */
  int MODEL_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_DECLARATION__NAME = OBJECT_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Model Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_DECLARATION_FEATURE_COUNT = OBJECT_DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.MonitorDeclarationImpl <em>Monitor Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.MonitorDeclarationImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getMonitorDeclaration()
   * @generated
   */
  int MONITOR_DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR_DECLARATION__NAME = OBJECT_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Monitor Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR_DECLARATION_FEATURE_COUNT = OBJECT_DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerDeclarationImpl <em>Analyzer Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerDeclarationImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getAnalyzerDeclaration()
   * @generated
   */
  int ANALYZER_DECLARATION = 4;

  /**
   * The number of structural features of the '<em>Analyzer Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYZER_DECLARATION_FEATURE_COUNT = OBJECT_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerImpl <em>Analyzer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getAnalyzer()
   * @generated
   */
  int ANALYZER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYZER__NAME = ANALYZER_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Analyzer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYZER_FEATURE_COUNT = ANALYZER_DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.PageDeclarationImpl <em>Page Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.PageDeclarationImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getPageDeclaration()
   * @generated
   */
  int PAGE_DECLARATION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_DECLARATION__NAME = OBJECT_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Page Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_DECLARATION_FEATURE_COUNT = OBJECT_DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.ObjectActionImpl <em>Object Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.ObjectActionImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getObjectAction()
   * @generated
   */
  int OBJECT_ACTION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_ACTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Object Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.ModelActionImpl <em>Model Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.ModelActionImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getModelAction()
   * @generated
   */
  int MODEL_ACTION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ACTION__NAME = OBJECT_ACTION__NAME;

  /**
   * The number of structural features of the '<em>Model Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ACTION_FEATURE_COUNT = OBJECT_ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.MonitorObjectActionImpl <em>Monitor Object Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.MonitorObjectActionImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getMonitorObjectAction()
   * @generated
   */
  int MONITOR_OBJECT_ACTION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR_OBJECT_ACTION__NAME = OBJECT_ACTION__NAME;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR_OBJECT_ACTION__VALUE = OBJECT_ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR_OBJECT_ACTION__METHOD = OBJECT_ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Monitor Object Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR_OBJECT_ACTION_FEATURE_COUNT = OBJECT_ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerObjectActionImpl <em>Analyzer Object Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerObjectActionImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getAnalyzerObjectAction()
   * @generated
   */
  int ANALYZER_OBJECT_ACTION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYZER_OBJECT_ACTION__NAME = OBJECT_ACTION__NAME;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYZER_OBJECT_ACTION__VALUE = OBJECT_ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYZER_OBJECT_ACTION__METHOD = OBJECT_ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Analyzer Object Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYZER_OBJECT_ACTION_FEATURE_COUNT = OBJECT_ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.PageObjectActionImpl <em>Page Object Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.impl.PageObjectActionImpl
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getPageObjectAction()
   * @generated
   */
  int PAGE_OBJECT_ACTION = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_OBJECT_ACTION__NAME = OBJECT_ACTION__NAME;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_OBJECT_ACTION__VALUE = OBJECT_ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_OBJECT_ACTION__METHOD = OBJECT_ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Page Object Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_OBJECT_ACTION_FEATURE_COUNT = OBJECT_ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.MonitorOperations <em>Monitor Operations</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.MonitorOperations
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getMonitorOperations()
   * @generated
   */
  int MONITOR_OPERATIONS = 12;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.AnalyzerOperations <em>Analyzer Operations</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.AnalyzerOperations
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getAnalyzerOperations()
   * @generated
   */
  int ANALYZER_OPERATIONS = 13;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.PageOperations <em>Page Operations</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.PageOperations
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getPageOperations()
   * @generated
   */
  int PAGE_OPERATIONS = 14;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sWEUIBK.ConnectionType <em>Connection Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sWEUIBK.ConnectionType
   * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getConnectionType()
   * @generated
   */
  int CONNECTION_TYPE = 15;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.Domainmodel <em>Domainmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domainmodel</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.Domainmodel
   * @generated
   */
  EClass getDomainmodel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.sWEUIBK.Domainmodel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.Domainmodel#getElements()
   * @see #getDomainmodel()
   * @generated
   */
  EReference getDomainmodel_Elements();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.sWEUIBK.Domainmodel#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.Domainmodel#getActions()
   * @see #getDomainmodel()
   * @generated
   */
  EReference getDomainmodel_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.ObjectDeclaration <em>Object Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Declaration</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.ObjectDeclaration
   * @generated
   */
  EClass getObjectDeclaration();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.ModelDeclaration <em>Model Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model Declaration</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.ModelDeclaration
   * @generated
   */
  EClass getModelDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.ModelDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.ModelDeclaration#getName()
   * @see #getModelDeclaration()
   * @generated
   */
  EAttribute getModelDeclaration_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.MonitorDeclaration <em>Monitor Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Monitor Declaration</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.MonitorDeclaration
   * @generated
   */
  EClass getMonitorDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.MonitorDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.MonitorDeclaration#getName()
   * @see #getMonitorDeclaration()
   * @generated
   */
  EAttribute getMonitorDeclaration_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.AnalyzerDeclaration <em>Analyzer Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Analyzer Declaration</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.AnalyzerDeclaration
   * @generated
   */
  EClass getAnalyzerDeclaration();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.Analyzer <em>Analyzer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Analyzer</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.Analyzer
   * @generated
   */
  EClass getAnalyzer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.Analyzer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.Analyzer#getName()
   * @see #getAnalyzer()
   * @generated
   */
  EAttribute getAnalyzer_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.PageDeclaration <em>Page Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page Declaration</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.PageDeclaration
   * @generated
   */
  EClass getPageDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.PageDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.PageDeclaration#getName()
   * @see #getPageDeclaration()
   * @generated
   */
  EAttribute getPageDeclaration_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.ObjectAction <em>Object Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Action</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.ObjectAction
   * @generated
   */
  EClass getObjectAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.ObjectAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.ObjectAction#getName()
   * @see #getObjectAction()
   * @generated
   */
  EAttribute getObjectAction_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.ModelAction <em>Model Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model Action</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.ModelAction
   * @generated
   */
  EClass getModelAction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.MonitorObjectAction <em>Monitor Object Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Monitor Object Action</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.MonitorObjectAction
   * @generated
   */
  EClass getMonitorObjectAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.MonitorObjectAction#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.MonitorObjectAction#getValue()
   * @see #getMonitorObjectAction()
   * @generated
   */
  EAttribute getMonitorObjectAction_Value();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.MonitorObjectAction#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.MonitorObjectAction#getMethod()
   * @see #getMonitorObjectAction()
   * @generated
   */
  EAttribute getMonitorObjectAction_Method();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.AnalyzerObjectAction <em>Analyzer Object Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Analyzer Object Action</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.AnalyzerObjectAction
   * @generated
   */
  EClass getAnalyzerObjectAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.AnalyzerObjectAction#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.AnalyzerObjectAction#getValue()
   * @see #getAnalyzerObjectAction()
   * @generated
   */
  EAttribute getAnalyzerObjectAction_Value();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.AnalyzerObjectAction#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.AnalyzerObjectAction#getMethod()
   * @see #getAnalyzerObjectAction()
   * @generated
   */
  EAttribute getAnalyzerObjectAction_Method();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sWEUIBK.PageObjectAction <em>Page Object Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page Object Action</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.PageObjectAction
   * @generated
   */
  EClass getPageObjectAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.PageObjectAction#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.PageObjectAction#getValue()
   * @see #getPageObjectAction()
   * @generated
   */
  EAttribute getPageObjectAction_Value();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sWEUIBK.PageObjectAction#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.PageObjectAction#getMethod()
   * @see #getPageObjectAction()
   * @generated
   */
  EAttribute getPageObjectAction_Method();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.sWEUIBK.MonitorOperations <em>Monitor Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Monitor Operations</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.MonitorOperations
   * @generated
   */
  EEnum getMonitorOperations();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.sWEUIBK.AnalyzerOperations <em>Analyzer Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Analyzer Operations</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.AnalyzerOperations
   * @generated
   */
  EEnum getAnalyzerOperations();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.sWEUIBK.PageOperations <em>Page Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Page Operations</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.PageOperations
   * @generated
   */
  EEnum getPageOperations();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.sWEUIBK.ConnectionType <em>Connection Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Connection Type</em>'.
   * @see org.xtext.example.mydsl.sWEUIBK.ConnectionType
   * @generated
   */
  EEnum getConnectionType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SWEUIBKFactory getSWEUIBKFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.DomainmodelImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getDomainmodel()
     * @generated
     */
    EClass DOMAINMODEL = eINSTANCE.getDomainmodel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAINMODEL__ELEMENTS = eINSTANCE.getDomainmodel_Elements();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAINMODEL__ACTIONS = eINSTANCE.getDomainmodel_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.ObjectDeclarationImpl <em>Object Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.ObjectDeclarationImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getObjectDeclaration()
     * @generated
     */
    EClass OBJECT_DECLARATION = eINSTANCE.getObjectDeclaration();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.ModelDeclarationImpl <em>Model Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.ModelDeclarationImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getModelDeclaration()
     * @generated
     */
    EClass MODEL_DECLARATION = eINSTANCE.getModelDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL_DECLARATION__NAME = eINSTANCE.getModelDeclaration_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.MonitorDeclarationImpl <em>Monitor Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.MonitorDeclarationImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getMonitorDeclaration()
     * @generated
     */
    EClass MONITOR_DECLARATION = eINSTANCE.getMonitorDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITOR_DECLARATION__NAME = eINSTANCE.getMonitorDeclaration_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerDeclarationImpl <em>Analyzer Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerDeclarationImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getAnalyzerDeclaration()
     * @generated
     */
    EClass ANALYZER_DECLARATION = eINSTANCE.getAnalyzerDeclaration();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerImpl <em>Analyzer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getAnalyzer()
     * @generated
     */
    EClass ANALYZER = eINSTANCE.getAnalyzer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANALYZER__NAME = eINSTANCE.getAnalyzer_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.PageDeclarationImpl <em>Page Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.PageDeclarationImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getPageDeclaration()
     * @generated
     */
    EClass PAGE_DECLARATION = eINSTANCE.getPageDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGE_DECLARATION__NAME = eINSTANCE.getPageDeclaration_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.ObjectActionImpl <em>Object Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.ObjectActionImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getObjectAction()
     * @generated
     */
    EClass OBJECT_ACTION = eINSTANCE.getObjectAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_ACTION__NAME = eINSTANCE.getObjectAction_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.ModelActionImpl <em>Model Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.ModelActionImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getModelAction()
     * @generated
     */
    EClass MODEL_ACTION = eINSTANCE.getModelAction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.MonitorObjectActionImpl <em>Monitor Object Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.MonitorObjectActionImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getMonitorObjectAction()
     * @generated
     */
    EClass MONITOR_OBJECT_ACTION = eINSTANCE.getMonitorObjectAction();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITOR_OBJECT_ACTION__VALUE = eINSTANCE.getMonitorObjectAction_Value();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITOR_OBJECT_ACTION__METHOD = eINSTANCE.getMonitorObjectAction_Method();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerObjectActionImpl <em>Analyzer Object Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.AnalyzerObjectActionImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getAnalyzerObjectAction()
     * @generated
     */
    EClass ANALYZER_OBJECT_ACTION = eINSTANCE.getAnalyzerObjectAction();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANALYZER_OBJECT_ACTION__VALUE = eINSTANCE.getAnalyzerObjectAction_Value();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANALYZER_OBJECT_ACTION__METHOD = eINSTANCE.getAnalyzerObjectAction_Method();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.impl.PageObjectActionImpl <em>Page Object Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.impl.PageObjectActionImpl
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getPageObjectAction()
     * @generated
     */
    EClass PAGE_OBJECT_ACTION = eINSTANCE.getPageObjectAction();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGE_OBJECT_ACTION__VALUE = eINSTANCE.getPageObjectAction_Value();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGE_OBJECT_ACTION__METHOD = eINSTANCE.getPageObjectAction_Method();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.MonitorOperations <em>Monitor Operations</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.MonitorOperations
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getMonitorOperations()
     * @generated
     */
    EEnum MONITOR_OPERATIONS = eINSTANCE.getMonitorOperations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.AnalyzerOperations <em>Analyzer Operations</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.AnalyzerOperations
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getAnalyzerOperations()
     * @generated
     */
    EEnum ANALYZER_OPERATIONS = eINSTANCE.getAnalyzerOperations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.PageOperations <em>Page Operations</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.PageOperations
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getPageOperations()
     * @generated
     */
    EEnum PAGE_OPERATIONS = eINSTANCE.getPageOperations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sWEUIBK.ConnectionType <em>Connection Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sWEUIBK.ConnectionType
     * @see org.xtext.example.mydsl.sWEUIBK.impl.SWEUIBKPackageImpl#getConnectionType()
     * @generated
     */
    EEnum CONNECTION_TYPE = eINSTANCE.getConnectionType();

  }

} //SWEUIBKPackage
