/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.SWEUIBKStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SWEUIBKStandaloneSetup extends SWEUIBKStandaloneSetupGenerated {
  public static void doSetup() {
    SWEUIBKStandaloneSetup _sWEUIBKStandaloneSetup = new SWEUIBKStandaloneSetup();
    _sWEUIBKStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
