/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.AbstractSWEUIBKRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SWEUIBKRuntimeModule extends AbstractSWEUIBKRuntimeModule {
}
